modLoader="javafml"
loaderVersion="[38,)"
license="Apache-2.0"
[[mods]]
modId="manyanarmor"
version="1.0.2"
displayName="Many An Armor"
updateJSONURL="https://infernalstudios.org/api/mods/manyanarmor/forge"
logoFile=""
authors="Infernal Studios"
description='''

'''
[[dependencies.manyanarmor]]
modId="forge"
mandatory=true
versionRange="[38,)"
ordering="NONE"
side="BOTH"
[[dependencies.manyanarmor]]
modId="minecraft"
mandatory=true
versionRange="[1.18,)"
ordering="NONE"
side="BOTH"